### ISSUE TITLE
Setup elasticsaerch, but stopped

### ISSUE THREAD

**Issue by fizyk** [ankane/setup-elasticsearch#4]
Hi, I got a question if setup-elasticsearch (or the rest of the excelent setup-* actions) could introduce a flag, that would skip starting the elasticsearch?

I'm planning to replace my own scripts installing elasticsearch: https://github.com/ClearcodeHQ/pytest-elasticsearch/blob/7cfa1e3add1f2ac266c19940ae913bb75e68db99/.install-elasticsearch.sh
To later start it by the pytest plugin I develop, but for version 8 i'm afraid too much ram is used (or I am doing something wrong on actions as I haven't been able to successfully start elasticsearch  >8 on actions by the plugin for the last year)

**Comment by ankane** [comment]
Hi @fizyk, thanks for the suggestion. However, I don't think it's common enough to add.
