### ISSUE TITLE
Cache and Speed of Setup

### ISSUE THREAD

**Issue by ishields** [ankane/setup-elasticsearch#5]
Hello, I'm using this to setup ES7 for CI and was wondering what the expected setup time was. I'm trying to speed up my CI and setting up ES seems to take about 32 seconds. I've tried using the cache option in the readme but it doesn't seem to ever find the cache.

<img width="1079" alt="image" src="https://github.com/ankane/setup-elasticsearch/assets/3834864/5d9a2420-9d0b-4f49-9540-129522a1fbb5">

<img width="731" alt="image" src="https://github.com/ankane/setup-elasticsearch/assets/3834864/6e82e8ea-77a3-480a-96f8-40ffae711da4">

**Comment by ankane** [comment]
Hi @ishields, caching appears to be working with a [simple test](https://github.com/ankane/setup-elasticsearch/blob/9479998180bd0848e7d0853dee5d195fa5f68e1d/.github/workflows/cache.yml) ([CI logs](https://github.com/ankane/setup-elasticsearch/actions/runs/8403869369/job/23014843507)). Note that caching has [some restrictions](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache).
